name: Deploy to staging repo

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Push to izaro-staging
        run: |
          git clone \
            "https://git:${{ secrets.STAGING_TOKEN }}@github.com/dinoiam/izaro-staging.git" /tmp/staging-repo
          rm -rf /tmp/staging-repo/*.html /tmp/staging-repo/*.json /tmp/staging-repo/*.svg /tmp/staging-repo/.github

          rsync -av --exclude='.github' --exclude='.git' ./ /tmp/staging-repo/

          cd /tmp/staging-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Deploy from izaro@$GITHUB_SHA" --allow-empty
          git push
